---
- name: Play #1 - execute show version across platforms
  hosts: all
  gather_facts: no
  connection: local
  vars:
    creds:
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - name: "** IOS XE ** Execute show version"
      ios_command:
        commands: "show version"
        provider: "{{ creds }}"
      register: xe_results
      when: "'csr1000v' in group_names"
    - debug: var=xe_results.stdout_lines
      when: "'csr1000v' in group_names"

    - name: "** IOS XR ** Execute show version"
      iosxr_command:
        commands: "show version"
        provider: "{{ creds }}"
      register: xr_results
      when: "'xrv' in group_names"
    - debug: var=xr_results.stdout_lines
      when: "'xrv' in group_names"

    - name: "** Junos ** Execute show version"
      junos_command:
        commands: "show version"
        provider: "{{ creds }}"
      register: junos_results
      when: "'vmx' in group_names"
    - debug: var=junos_results.stdout_lines 
      when: "'vmx' in group_names"
